# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


def ReturnSizePolicy(policy,hasHeightForWidth):
    sizePolicy = QtWidgets.QSizePolicy(policy, policy)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(hasHeightForWidth)
    return sizePolicy


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(10,10)

        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Maximum,self.centralWidget.sizePolicy().hasHeightForWidth()))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Maximum,self.widget.sizePolicy().hasHeightForWidth()))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")

        self.ZToolbar_widget = QtWidgets.QWidget(MainWindow)
        self.ZToolbar = QtWidgets.QGridLayout(self.ZToolbar_widget)
        self.ZToolbar.setContentsMargins(11, 11, 11, 11)
        self.ZToolbar.setSpacing(15)
        self.ZToolbar.setObjectName("ZToolbar")
        self.verticalLayout_2.addWidget(self.ZToolbar_widget)

        self.selectrectButton = QtWidgets.QPushButton(self.widget)
        self.selectrectButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.selectrectButton.sizePolicy().hasHeightForWidth()))
        self.selectrectButton.setMinimumSize(QtCore.QSize(30, 30))
        self.selectrectButton.setMaximumSize(QtCore.QSize(30, 30))
        self.selectrectButton.setText("")
        self.selectrectButton.setToolTip('Rectangle selection')
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/selection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectrectButton.setIcon(icon2)
        self.selectrectButton.setCheckable(True)
        self.selectrectButton.setObjectName("selectrectButton")
        self.gridLayout.addWidget(self.selectrectButton, 0, 1, 1, 1)

        self.indicatePeriodicityButton = QtWidgets.QPushButton(self.widget)
        self.indicatePeriodicityButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.indicatePeriodicityButton.sizePolicy().hasHeightForWidth()))
        self.indicatePeriodicityButton.setMinimumSize(QtCore.QSize(30, 30))
        self.indicatePeriodicityButton.setMaximumSize(QtCore.QSize(30, 30))
        self.indicatePeriodicityButton.setText("")
        icon_indicate_periodicity = QtGui.QIcon()
        icon_indicate_periodicity.addPixmap(QtGui.QPixmap("images/indicate_periodicity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.indicatePeriodicityButton.setIcon(icon_indicate_periodicity)
        self.indicatePeriodicityButton.setCheckable(True)
        self.indicatePeriodicityButton.setObjectName("indicatePeriodicityButton")
        self.indicatePeriodicityButton.setToolTip('Set desired periodicity')

        self.selectpolyButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectpolyButton.sizePolicy().hasHeightForWidth())
        self.selectpolyButton.setSizePolicy(sizePolicy)
        self.selectpolyButton.setMinimumSize(QtCore.QSize(30, 30))
        self.selectpolyButton.setMaximumSize(QtCore.QSize(30, 30))
        self.selectpolyButton.setText("")
        self.selectpolyButton.setToolTip('Polygon selection')
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/selection-poly.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectpolyButton.setIcon(icon6)
        self.selectpolyButton.setCheckable(True)
        self.selectpolyButton.setObjectName("selectpolyButton")
        self.gridLayout.addWidget(self.selectpolyButton, 0, 0, 1, 1)

        self.UnselectButton = QtWidgets.QPushButton(self.widget)
        self.UnselectButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.UnselectButton.sizePolicy().hasHeightForWidth()))
        self.UnselectButton.setMinimumSize(QtCore.QSize(30, 30))
        self.UnselectButton.setMaximumSize(QtCore.QSize(30, 30))
        self.UnselectButton.setText("")
        icon6_0 = QtGui.QIcon()
        icon6_0.addPixmap(QtGui.QPixmap("images/unselect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UnselectButton.setIcon(icon6_0)
        self.UnselectButton.setCheckable(False)
        self.UnselectButton.setObjectName("UnselectButton")
        self.UnselectButton.setToolTip('De-select')
        self.gridLayout.addWidget(self.UnselectButton,0,2, 1, 1)

        self.invertSelectionButton = QtWidgets.QPushButton(self.widget)
        self.invertSelectionButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.invertSelectionButton.sizePolicy().hasHeightForWidth()))
        self.invertSelectionButton.setMinimumSize(QtCore.QSize(30, 30))
        self.invertSelectionButton.setMaximumSize(QtCore.QSize(30, 30))
        self.invertSelectionButton.setText("")
        icon6_0 = QtGui.QIcon()
        icon6_0.addPixmap(QtGui.QPixmap("images/invertSelection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.invertSelectionButton.setIcon(icon6_0)
        self.invertSelectionButton.setCheckable(False)
        self.invertSelectionButton.setObjectName("invertSelectionButton")
        self.invertSelectionButton.setToolTip('Invert selection')
        self.gridLayout.addWidget(self.invertSelectionButton,0,3, 1, 1)

        self.uniformZButton = QtWidgets.QPushButton(self.widget)
        self.uniformZButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.uniformZButton.sizePolicy().hasHeightForWidth()))
        self.uniformZButton.setMinimumSize(QtCore.QSize(30, 30))
        self.uniformZButton.setMaximumSize(QtCore.QSize(30, 30))
        self.uniformZButton.setText("")
        icon6_0 = QtGui.QIcon()
        icon6_0.addPixmap(QtGui.QPixmap("images/uniform_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uniformZButton.setIcon(icon6_0)
        self.uniformZButton.setCheckable(False)
        self.uniformZButton.setObjectName("uniformZButton")
        self.uniformZButton.setToolTip('Spatially uniform Z')
        self.gridLayout.addWidget(self.uniformZButton,2,1, 1, 1)

        self.desiredExternalAppearanceModeButton = QtWidgets.QPushButton(self.widget)
        self.desiredExternalAppearanceModeButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.desiredExternalAppearanceModeButton.sizePolicy().hasHeightForWidth()))
        self.desiredExternalAppearanceModeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.desiredExternalAppearanceModeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.desiredExternalAppearanceModeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/image_hist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.desiredExternalAppearanceModeButton.setIcon(icon4)
        self.desiredExternalAppearanceModeButton.setCheckable(True)
        self.desiredExternalAppearanceModeButton.setObjectName("desiredImageHistModeButton")
        self.desiredExternalAppearanceModeButton.setToolTip('Select external desired region')
        self.gridLayout.addWidget(self.desiredExternalAppearanceModeButton, 1, 0, 1, 1)

        self.desiredAppearanceModeButton = QtWidgets.QPushButton(self.widget)
        self.desiredAppearanceModeButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.desiredAppearanceModeButton.sizePolicy().hasHeightForWidth()))
        self.desiredAppearanceModeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.desiredAppearanceModeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.desiredAppearanceModeButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/hist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.desiredAppearanceModeButton.setIcon(icon4)
        self.desiredAppearanceModeButton.setCheckable(True)
        self.desiredAppearanceModeButton.setObjectName("desiredHistModeButton")
        self.desiredAppearanceModeButton.setToolTip('Select desired region')
        self.gridLayout.addWidget(self.desiredAppearanceModeButton, 1,1, 1, 1)

        self.ZdisplayButton = QtWidgets.QPushButton(self.widget)
        self.ZdisplayButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.ZdisplayButton.sizePolicy().hasHeightForWidth()))
        self.ZdisplayButton.setMinimumSize(QtCore.QSize(30, 30))
        self.ZdisplayButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ZdisplayButton.setText("")
        icon_Zdisplay = QtGui.QIcon()
        icon_Zdisplay.addPixmap(QtGui.QPixmap("images/Z_letter.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZdisplayButton.setIcon(icon_Zdisplay)
        self.ZdisplayButton.setCheckable(True)
        self.ZdisplayButton.setObjectName("ZdisplayButton")
        self.ZdisplayButton.setToolTip('Toggle Z display')
        self.gridLayout.addWidget(self.ZdisplayButton, 2,0, 1, 1)

        self.undo_scribble_button = QtWidgets.QPushButton(self.widget)
        self.undo_scribble_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.undo_scribble_button.sizePolicy().hasHeightForWidth()))
        self.undo_scribble_button.setMinimumSize(QtCore.QSize(30, 30))
        self.undo_scribble_button.setMaximumSize(QtCore.QSize(30, 30))
        self.undo_scribble_button.setText("")
        icon_Undo_scribble = QtGui.QIcon()
        icon_Undo_scribble.addPixmap(QtGui.QPixmap("images/undo_scribble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_scribble_button.setIcon(icon_Undo_scribble)
        self.undo_scribble_button.setCheckable(False)
        self.undo_scribble_button.setObjectName("undo_scribble_button")
        self.gridLayout.addWidget(self.undo_scribble_button, 3, 2, 1, 1)
        self.undo_scribble_button.setEnabled(False)
        self.undo_scribble_button.setToolTip('Undo scribble/imprint')

        self.redo_scribble_button = QtWidgets.QPushButton(self.widget)
        self.redo_scribble_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.redo_scribble_button.sizePolicy().hasHeightForWidth()))
        self.redo_scribble_button.setMinimumSize(QtCore.QSize(30, 30))
        self.redo_scribble_button.setMaximumSize(QtCore.QSize(30, 30))
        self.redo_scribble_button.setText("")
        icon_Redo_scribble = QtGui.QIcon()
        icon_Redo_scribble.addPixmap(QtGui.QPixmap("images/redo_scribble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redo_scribble_button.setIcon(icon_Redo_scribble)
        self.redo_scribble_button.setCheckable(False)
        self.redo_scribble_button.setObjectName("redo_scribble_button")
        self.redo_scribble_button.setToolTip('Redo scribble/imprint')
        self.gridLayout.addWidget(self.redo_scribble_button, 3, 3, 1, 1)
        self.redo_scribble_button.setEnabled(False)

        # Imprinting translation buttons:
        for button_num,button in enumerate(['left','right','up','down']):
            setattr(self,button+'_imprinting_button',QtWidgets.QPushButton(self.widget))
            cur_button = getattr(self,button+'_imprinting_button')
            cur_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,cur_button.sizePolicy().hasHeightForWidth()))
            cur_button.setMinimumSize(QtCore.QSize(30, 30))
            cur_button.setMaximumSize(QtCore.QSize(30, 30))
            cur_button.setText("")
            cur_icon = QtGui.QIcon()
            cur_icon.addPixmap(QtGui.QPixmap("images/translate_%s.png"%(button)), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            cur_button.setIcon(cur_icon)
            cur_button.setCheckable(False)
            cur_button.setObjectName(button+'_imprinting_button')
            self.gridLayout.addWidget(cur_button, 4, button_num, 1, 1)
            cur_button.setEnabled(False)
            cur_button.setToolTip('Move imprinting '+button)

        # Imprinting dimensions change buttons:
        for button_num,button in enumerate(['narrower','wider','taller','shorter']):
            setattr(self,'%s_imprinting_button'%(button),QtWidgets.QPushButton(self.widget))
            cur_button = getattr(self,'%s_imprinting_button'%(button))
            cur_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,cur_button.sizePolicy().hasHeightForWidth()))
            cur_button.setMinimumSize(QtCore.QSize(30, 30))
            cur_button.setMaximumSize(QtCore.QSize(30, 30))
            cur_button.setText("")
            cur_icon = QtGui.QIcon()
            cur_icon.addPixmap(QtGui.QPixmap("images/make_%s.png"%(button)), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            cur_button.setIcon(cur_icon)
            cur_button.setCheckable(False)
            cur_button.setObjectName(button+'_imprinting_button')
            self.gridLayout.addWidget(cur_button, 5, button_num, 1, 1)
            cur_button.setEnabled(False)
            cur_button.setToolTip('Make imprinting '+button)

        self.undoZ_button = QtWidgets.QPushButton(self.widget)
        self.undoZ_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.undoZ_button.sizePolicy().hasHeightForWidth()))
        self.undoZ_button.setMinimumSize(QtCore.QSize(30, 30))
        self.undoZ_button.setMaximumSize(QtCore.QSize(30, 30))
        self.undoZ_button.setText("")
        icon_UndoZ = QtGui.QIcon()
        icon_UndoZ.addPixmap(QtGui.QPixmap("images/undo_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoZ_button.setIcon(icon_UndoZ)
        self.undoZ_button.setCheckable(False)
        self.undoZ_button.setObjectName("undo_Z_button")
        self.gridLayout.addWidget(self.undoZ_button, 3, 0, 1, 1)
        self.undoZ_button.setEnabled(False)
        self.undoZ_button.setToolTip('Undo Z manipulation')

        self.redoZ_button = QtWidgets.QPushButton(self.widget)
        self.redoZ_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.redoZ_button.sizePolicy().hasHeightForWidth()))
        self.redoZ_button.setMinimumSize(QtCore.QSize(30, 30))
        self.redoZ_button.setMaximumSize(QtCore.QSize(30, 30))
        self.redoZ_button.setText("")
        icon_redoZ = QtGui.QIcon()
        icon_redoZ.addPixmap(QtGui.QPixmap("images/redo_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redoZ_button.setIcon(icon_redoZ)
        self.redoZ_button.setCheckable(False)
        self.redoZ_button.setObjectName("redoZ_button")
        self.gridLayout.addWidget(self.redoZ_button, 3, 1, 1, 1)
        self.redoZ_button.setEnabled(False)
        self.redoZ_button.setToolTip('Redo Z manipulation')

        self.auto_hist_temperature_mode_button = QtWidgets.QPushButton(self.widget)
        self.auto_hist_temperature_mode_button.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.auto_hist_temperature_mode_button.sizePolicy().hasHeightForWidth()))
        self.auto_hist_temperature_mode_button.setMinimumSize(QtCore.QSize(30, 30))
        self.auto_hist_temperature_mode_button.setMaximumSize(QtCore.QSize(30, 30))
        self.auto_hist_temperature_mode_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/auto_temperature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auto_hist_temperature_mode_button.setIcon(icon5)
        self.auto_hist_temperature_mode_button.setCheckable(True)
        self.auto_hist_temperature_mode_button.setObjectName("auto_hist_temperature_mode_button")
        self.gridLayout.addWidget(self.auto_hist_temperature_mode_button, 2, 2, 1, 1)
        self.auto_hist_temperature_mode_button.setToolTip('Automatic histogram temperature')

        self.verticalLayout_2.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.canvas = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 549, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuImage = QtWidgets.QMenu(self.menuBar)
        self.menuImage.setObjectName("menuImage")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.fileToolbar = QtWidgets.QToolBar(MainWindow)
        self.fileToolbar.setIconSize(QtCore.QSize(16, 16))
        self.fileToolbar.setObjectName("fileToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.fileToolbar)

        MainWindow.addToolBarBreak()#.addItem(spacerItem2)


        # self.ZToolbar = QtWidgets.QToolBar(MainWindow)
        # self.ZToolbar.setIconSize(QtCore.QSize(25,25))
        # self.ZToolbar.setObjectName("ZToolbar")
        # self.ZToolbar.setOrientation(QtCore.Qt.Horizontal)
        # MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ZToolbar)

        self.Scribble_Toolbar = QtWidgets.QToolBar(MainWindow)
        self.Scribble_Toolbar.setIconSize(QtCore.QSize(25,25))
        self.Scribble_Toolbar.setObjectName("Scribble_Toolbar")
        self.Scribble_Toolbar.setOrientation(QtCore.Qt.Horizontal)
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.Scribble_Toolbar)

        self.ZToolbar2 = QtWidgets.QToolBar(MainWindow)
        self.ZToolbar2.setIconSize(QtCore.QSize(25,25))
        self.ZToolbar2.setObjectName("ZToolbar2")
        self.ZToolbar2.setOrientation(QtCore.Qt.Horizontal)
        # MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea if MainWindow.canvas.display_zoom_factor>1 else QtCore.Qt.BottomToolBarArea, self.ZToolbar2)
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.ZToolbar2)

        icon_scribble_reset = QtGui.QIcon()
        icon_scribble_reset.addPixmap(QtGui.QPixmap("images/scribble_reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScribbleReset = QtWidgets.QAction(icon=icon_scribble_reset,parent=self.Scribble_Toolbar)
        self.actionScribbleReset.setObjectName("actionScribbleReset")
        # self.actionScribbleReset.setEnabled(True)

        icon_scribble_reset = QtGui.QIcon()
        icon_scribble_reset.addPixmap(QtGui.QPixmap("images/apply_scribble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApplyScrible = QtWidgets.QAction(icon=icon_scribble_reset,parent=self.Scribble_Toolbar)
        self.actionApplyScrible.setObjectName("actionApplyScrible")

        icon_scribble_reset = QtGui.QIcon()
        icon_scribble_reset.addPixmap(QtGui.QPixmap("images/loop_apply_scribble.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoopApplyScrible = QtWidgets.QAction(icon=icon_scribble_reset,parent=self.Scribble_Toolbar)
        self.actionLoopApplyScrible.setObjectName("actionLoopApplyScrible")

        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton = QtWidgets.QPushButton(icon=icon8,parent=self.Scribble_Toolbar)
        self.penButton.setIcon(icon8)
        self.penButton.setCheckable(True)
        self.penButton.setObjectName("penButton")
        self.penButton.setToolTip('Pen')

        # icon_brush = QtGui.QIcon()
        # icon_brush.addPixmap(QtGui.QPixmap("images/paint-brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.brushButton = QtWidgets.QPushButton(icon=icon_brush,parent=self.Scribble_Toolbar)
        # self.brushButton.setCheckable(True)
        # self.brushButton.setObjectName("brushButton")

        icon_dropper = QtGui.QIcon()
        icon_dropper.addPixmap(QtGui.QPixmap("images/pipette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dropperButton = QtWidgets.QPushButton(parent=self.widget,icon=icon_dropper)
        self.dropperButton.setCheckable(True)
        self.dropperButton.setObjectName("dropperButton")
        self.dropperButton.setToolTip('Eyedropper')

        line_icon = QtGui.QIcon()
        line_icon.addPixmap(QtGui.QPixmap("images/layer-shape-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineButton = QtWidgets.QPushButton(parent=self.Scribble_Toolbar,icon=line_icon)
        self.lineButton.setCheckable(True)
        self.lineButton.setObjectName("lineButton")
        self.lineButton.setToolTip('Straight line drawing')

        # self.polygonButton.setMinimumSize(QtCore.QSize(30, 30))
        # self.polygonButton.setMaximumSize(QtCore.QSize(30, 30))
        # self.polygonButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/layer-shape-polygon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polygonButton = QtWidgets.QPushButton(parent=self.Scribble_Toolbar,icon=icon11)
        # self.polygonButton.setIcon(icon11)
        self.polygonButton.setCheckable(True)
        self.polygonButton.setObjectName("polygonButton")
        self.polygonButton.setToolTip('Polygon drawing')

        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/layer-shape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectButton = QtWidgets.QPushButton(parent=self.Scribble_Toolbar,icon=icon12)
        self.rectButton.setCheckable(True)
        self.rectButton.setObjectName("rectButton")
        self.rectButton.setToolTip('Rectangle drawing')

        icon_image_input = QtGui.QIcon()
        icon_image_input.addPixmap(QtGui.QPixmap("images/image_input.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.im_inputButton = QtWidgets.QPushButton(parent=self.Scribble_Toolbar,icon=icon_image_input)
        self.im_inputButton.setCheckable(True)
        self.im_inputButton.setObjectName("im_inputButton")
        self.im_inputButton.setEnabled(False)
        self.im_inputButton.setToolTip('Set imprinting rectangle (Using transparent color)')

        icon_im_input_auto_location = QtGui.QIcon()
        icon_im_input_auto_location.addPixmap(QtGui.QPixmap("images/image_input_noDC.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.im_input_auto_locationButton = QtWidgets.QPushButton(parent=self.Scribble_Toolbar,icon=icon_im_input_auto_location)
        self.im_input_auto_locationButton.setCheckable(True)
        self.im_input_auto_locationButton.setObjectName("im_input_auto_locationButton")
        self.im_input_auto_locationButton.setEnabled(False)
        self.im_input_auto_locationButton.setToolTip('Set boundaries for automatic imprinting location (Using transparent color)')

        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/layer-shape-ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ellipseButton = QtWidgets.QPushButton(parent=self.Scribble_Toolbar,icon=icon13)
        # self.ellipseButton.setIcon(icon13)
        self.ellipseButton.setCheckable(True)
        self.ellipseButton.setObjectName("ellipseButton")
        self.ellipseButton.setToolTip('Ellipse drawing')
        # self.gridLayout.addWidget(self.ellipseButton, 7, 0, 1, 1)

        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionClearImage = QtWidgets.QAction(MainWindow)
        self.actionClearImage.setObjectName("actionClearImage")

        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("images/blue-folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenImage.setIcon(icon16)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionOpenImage.setToolTip('Load LR image')

        self.actionLoad_Z = QtWidgets.QAction(MainWindow)
        icon_load_Z = QtGui.QIcon()
        icon_load_Z.addPixmap(QtGui.QPixmap("images/Z_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Z.setIcon(icon_load_Z)
        self.actionLoad_Z.setObjectName("actionLoad_Z")
        self.actionLoad_Z.setToolTip('Load Z map')

        self.actionLoad_Z_mask = QtWidgets.QAction(MainWindow)
        icon_load_Z_mask = QtGui.QIcon()
        icon_load_Z_mask.addPixmap(QtGui.QPixmap("images/Z_mask_load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Z_mask.setIcon(icon_load_Z_mask)
        self.actionLoad_Z_mask.setObjectName("actionLoad_Z_mask")
        self.actionLoad_Z_mask.setToolTip('Load Z map to infer selection')

        self.estimatedKenrelButton = QtWidgets.QPushButton(self.fileToolbar)
        self.estimatedKenrelButton.setSizePolicy(ReturnSizePolicy(QtWidgets.QSizePolicy.Fixed,self.estimatedKenrelButton.sizePolicy().hasHeightForWidth()))
        self.estimatedKenrelButton.setMinimumSize(QtCore.QSize(30, 30))
        self.estimatedKenrelButton.setMaximumSize(QtCore.QSize(30, 30))
        self.estimatedKenrelButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/hist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.estimatedKenrelButton.setIcon(icon4)
        self.estimatedKenrelButton.setCheckable(True)
        self.estimatedKenrelButton.setObjectName("desiredHistModeButton")
        self.estimatedKenrelButton.setToolTip('Use estimated SR kernel')

        self.actionProcessRandZ = QtWidgets.QAction(MainWindow)
        # self.actionProcessRandZ.setText("Random Z")
        icon_randomZ = QtGui.QIcon()
        icon_randomZ.addPixmap(QtGui.QPixmap("images/random_l1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProcessRandZ.setIcon(icon_randomZ)
        self.actionProcessRandZ.setObjectName("actionProcessRandZ")
        self.actionProcessRandZ.setToolTip('Produce random images')

        self.actionProcessLimitedRandZ = QtWidgets.QAction(MainWindow)
        icon_limited_randomZ = QtGui.QIcon()
        icon_limited_randomZ.addPixmap(QtGui.QPixmap("images/random_l1_limited.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProcessLimitedRandZ.setIcon(icon_limited_randomZ)
        self.actionProcessLimitedRandZ.setObjectName("actionProcessLimitedRandZ")
        self.actionProcessLimitedRandZ.setToolTip('Produce random images close to current')

        # self.randomLimitingWeightBox = QtWidgets.QLineEdit(MainWindow)
        self.randomLimitingWeightBox_Enabled = False
        if self.randomLimitingWeightBox_Enabled:
            self.randomLimitingWeightBox = QtWidgets.QDoubleSpinBox(MainWindow)
            self.randomLimitingWeightBox.setObjectName("randomLimitingWeightBox")
            self.randomLimitingWeightBox.setValue(1.)
            # self.randomLimitingWeightBox.setText('1')
            self.randomLimitingWeightBox.setMaximum(200)
            self.randomLimitingWeightBox.setToolTip('Random images limitation weight')
            # self.randomLimitingWeightBox.setSingleStep(0.1)

        self.periodicity_mag_1 = QtWidgets.QDoubleSpinBox(MainWindow)
        self.periodicity_mag_1.setObjectName("periodicity_mag_1")
        self.periodicity_mag_1.setValue(1.)
        self.periodicity_mag_1.setMaximum(200)
        self.periodicity_mag_1.setSingleStep(0.1)
        self.periodicity_mag_1.setDecimals(1)
        self.periodicity_mag_1.setToolTip('Primary period length')
        self.periodicity_mag_2 = QtWidgets.QDoubleSpinBox(MainWindow)
        self.periodicity_mag_2.setObjectName("periodicity_mag_2")
        self.periodicity_mag_2.setValue(1.)
        self.periodicity_mag_2.setMaximum(200)
        self.periodicity_mag_2.setSingleStep(0.1)
        self.periodicity_mag_2.setDecimals(1)
        self.periodicity_mag_2.setToolTip('Secondary period length')

        icon_copyRandZ = QtGui.QIcon()
        # icon_copyRandZ = QtGui.QIcon(QtGui.QPixmap("images/randoms2default.png"))
        icon_copyRandZ.addPixmap(QtGui.QPixmap("images/randoms2default.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.actionCopyFromRandom = QtWidgets.QAction(icon=icon_copyRandZ,parent=MainWindow)
        self.actionCopyFromRandom = QtWidgets.QPushButton(icon=icon_copyRandZ,parent=MainWindow)
        # self.actionCopyFromRandom.setIcon(icon_copyRandZ)
        self.actionCopyFromRandom.setObjectName("actionCopyFromRandom")
        self.actionCopyFromRandom.setEnabled(False)
        self.actionCopyFromRandom.setToolTip('Copy displayed random region to Z')

        self.actionCopy2Random = QtWidgets.QPushButton(MainWindow)
        icon_copyDefault2RandZ = QtGui.QIcon()
        icon_copyDefault2RandZ = QtGui.QIcon()
        icon_copyDefault2RandZ.addPixmap(QtGui.QPixmap("images/default2randoms.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy2Random.setIcon(icon_copyDefault2RandZ)
        self.actionCopy2Random.setObjectName("actionCopy2Random")
        self.actionCopy2Random.setToolTip('Copy region from Z to random images')
        # self.actionCopy2Random.setEnabled(True)

        self.DisplayedImageSelectionButton = QtWidgets.QComboBox(MainWindow)
        # self.DisplayedImageSelectionButton.setText("Random Z")
        # self.DisplayedImageSelectionButton.addItem('')
        # self.DisplayedImageSelectionButton.addItems([str(i+1) for i in range(self.num_random_Zs)])
        self.DisplayedImageSelectionButton.setObjectName("DisplayedImageSelectionButton")
        self.DisplayedImageSelectionButton.setEnabled(False)
        self.DisplayedImageSelectionButton.setToolTip('Displayed image')

        patch_opt_behavior_icon = QtGui.QIcon()
        patch_opt_behavior_icon.addPixmap(QtGui.QPixmap("images/layer-shape-ellipse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.special_behaviorButton = QtWidgets.QPushButton(parent=self.ZToolbar2,icon=patch_opt_behavior_icon)
        self.special_behaviorButton.setCheckable(True)
        self.special_behaviorButton.setObjectName("special_behaviorButton")
        self.special_behaviorButton.setToolTip('Toggle special behavior')

        self.actionIncreaseSTD = QtWidgets.QAction(MainWindow)
        # self.actionIncreaseSTD.setText("Increase STD")
        self.actionIncreaseSTD.setObjectName("actionIncreaseSTD")
        icon_sigmaUp = QtGui.QIcon()
        icon_sigmaUp.addPixmap(QtGui.QPixmap("images/sigma_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncreaseSTD.setIcon(icon_sigmaUp)
        self.actionIncreaseSTD.setToolTip('Increase local STD (Magnitude)')

        self.actionDecreaseSTD = QtWidgets.QAction(MainWindow)
        # self.actionDecreaseSTD.setText("Decrease STD")
        self.actionDecreaseSTD.setObjectName("actionDecreaseSTD")
        icon_sigmadown = QtGui.QIcon()
        icon_sigmadown.addPixmap(QtGui.QPixmap("images/sigma_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDecreaseSTD.setIcon(icon_sigmadown)
        self.actionDecreaseSTD.setToolTip('Decrease local STD (Magnitude)')

        self.STD_increment = QtWidgets.QDoubleSpinBox(MainWindow)
        self.STD_increment.setObjectName("STD_increment")
        self.STD_increment.setValue(0.03)
        self.STD_increment.setRange(0,0.3)
        self.STD_increment.setSingleStep(0.01)
        self.STD_increment.setDecimals(2)
        self.STD_increment.setToolTip('STD/Brightness change')

        self.actionDecreaseTV = QtWidgets.QAction(MainWindow)
        self.actionDecreaseTV.setObjectName("actionDecreaseTV")
        icon_TVdown = QtGui.QIcon()
        icon_TVdown.addPixmap(QtGui.QPixmap("images/TV_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDecreaseTV.setIcon(icon_TVdown)
        self.actionDecreaseTV.setToolTip('Decrease TV')

        self.actionImitateHist = QtWidgets.QAction(MainWindow)
        self.actionImitateHist.setObjectName("actionImitateHist")
        icon_hist_imitation = QtGui.QIcon()
        icon_hist_imitation.addPixmap(QtGui.QPixmap("images/hist_imitation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImitateHist.setIcon(icon_hist_imitation)
        self.actionImitateHist.setEnabled(False)
        self.actionImitateHist.setToolTip('Encourage desired histogram')

        self.actionImitatePatchHist = QtWidgets.QAction(MainWindow)
        self.actionImitatePatchHist.setObjectName("actionImitatePatchHist")
        icon_patch_hist_imitation = QtGui.QIcon()
        icon_patch_hist_imitation.addPixmap(QtGui.QPixmap("images/hist_imitation_patch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImitatePatchHist.setIcon(icon_patch_hist_imitation)
        self.actionImitatePatchHist.setEnabled(False)
        self.actionImitatePatchHist.setToolTip('Encourage desired mean-less (normalized) patches')

        # self.actionMatchSliders = QtWidgets.QAction(MainWindow)
        # self.actionMatchSliders.setObjectName("actionMatchSliders")
        # icon_match_sliders = QtGui.QIcon()
        # icon_match_sliders.addPixmap(QtGui.QPixmap("images/sliders_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.actionMatchSliders.setIcon(icon_match_sliders)

        self.actionFoolAdversary = QtWidgets.QAction(MainWindow)
        self.actionFoolAdversary.setObjectName("actionFoolAdversary")
        icon_pixmap = QtGui.QPixmap("images/adversary.png")
        # icon_pixmap.scaledToWidth(40)
        icon_adversary = QtGui.QIcon()
        icon_adversary.addPixmap(icon_pixmap, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon_adversary.actualSize(QtCore.QSize(60, 60))
        self.actionFoolAdversary.setIcon(icon_adversary)
        self.actionFoolAdversary.setToolTip('Fool discriminator')

        self.actionIncreasePeriodicity = QtWidgets.QAction(MainWindow)
        self.actionIncreasePeriodicity.setObjectName("actionIncreasePeriodicity")
        icon_pixmap = QtGui.QPixmap("images/indicate_periodicity_2D.png")
        icon_periodicity = QtGui.QIcon()
        icon_periodicity.addPixmap(icon_pixmap, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncreasePeriodicity.setIcon(icon_periodicity)
        self.actionIncreasePeriodicity.setEnabled(False)
        self.actionIncreasePeriodicity.setToolTip('Increase 2D periodicity')

        self.actionIncreasePeriodicity_1D = QtWidgets.QAction(MainWindow)
        self.actionIncreasePeriodicity_1D.setObjectName("actionIncreasePeriodicity_1D")
        icon_pixmap = QtGui.QPixmap("images/indicate_periodicity_1D.png")
        icon_periodicity = QtGui.QIcon()
        icon_periodicity.addPixmap(icon_pixmap, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncreasePeriodicity_1D.setIcon(icon_periodicity)
        self.actionIncreasePeriodicity_1D.setEnabled(False)
        self.actionIncreasePeriodicity_1D.setToolTip('Increase 1D periodicity')

        self.actionSaveImageAndData = QtWidgets.QAction(MainWindow)
        icon17_0 = QtGui.QIcon()
        icon17_0.addPixmap(QtGui.QPixmap("images/Save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveImageAndData.setIcon(icon17_0)
        self.actionSaveImageAndData.setObjectName("actionSaveImageAndData")
        self.actionSaveImageAndData.setToolTip('Save image, Z and scribble data')

        self.actionDecreaseDisplayZoom = QtWidgets.QAction(MainWindow)
        icon17_0 = QtGui.QIcon()
        icon17_0.addPixmap(QtGui.QPixmap("images/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDecreaseDisplayZoom.setIcon(icon17_0)
        self.actionDecreaseDisplayZoom.setObjectName("actionDecreaseDisplayZoom")
        self.actionDecreaseDisplayZoom.setToolTip('Save image, Z and scribble data')

        self.actionIncreaseDisplayZoom = QtWidgets.QAction(MainWindow)
        icon17_0 = QtGui.QIcon()
        icon17_0.addPixmap(QtGui.QPixmap("images/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncreaseDisplayZoom.setIcon(icon17_0)
        self.actionIncreaseDisplayZoom.setObjectName("actionIncreaseDisplayZoom")
        self.actionIncreaseDisplayZoom.setToolTip('Save image, Z and scribble data')

        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveImage.setIcon(icon17)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionInvertColors = QtWidgets.QAction(MainWindow)
        self.actionInvertColors.setObjectName("actionInvertColors")
        self.actionFlipHorizontal = QtWidgets.QAction(MainWindow)
        self.actionFlipHorizontal.setObjectName("actionFlipHorizontal")
        self.actionFlipVertical = QtWidgets.QAction(MainWindow)
        self.actionFlipVertical.setObjectName("actionFlipVertical")
        self.actionNewImage = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("images/document-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewImage.setIcon(icon18)
        self.actionNewImage.setObjectName("actionNewImage")
        self.actionNewImage.setToolTip('Synthetically downscale an HR image')
        self.actionBold = QtWidgets.QAction(MainWindow)
        self.actionBold.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("images/edit-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon19)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(MainWindow)
        self.actionItalic.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("images/edit-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon20)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtWidgets.QAction(MainWindow)
        self.actionUnderline.setCheckable(True)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("images/edit-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon21)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionFillShapes = QtWidgets.QAction(MainWindow)
        self.actionFillShapes.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("images/paint-can-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFillShapes.setIcon(icon22)
        self.actionFillShapes.setObjectName("actionFillShapes")
        self.menuFIle.addAction(self.actionNewImage)
        self.menuFIle.addAction(self.actionOpenImage)
        self.menuFIle.addAction(self.actionSaveImage)
        self.menuFIle.addAction(self.actionSaveImageAndData)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClearImage)
        self.menuImage.addAction(self.actionInvertColors)
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.actionFlipHorizontal)
        self.menuImage.addAction(self.actionFlipVertical)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuImage.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.fileToolbar.addAction(self.actionNewImage)
        self.fileToolbar.addAction(self.actionOpenImage)
        self.fileToolbar.addWidget(self.estimatedKenrelButton)
        self.fileToolbar.addAction(self.actionLoad_Z)
        self.fileToolbar.addAction(self.actionLoad_Z_mask)
        self.fileToolbar.addAction(self.actionSaveImage)
        self.fileToolbar.addAction(self.actionSaveImageAndData)
        self.fileToolbar.addAction(self.actionDecreaseDisplayZoom)
        self.fileToolbar.addAction(self.actionIncreaseDisplayZoom)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "Explorable SR"+(' (x%d)'%(self.display_zoom_factor) if self.display_zoom_factor>1 else '')))
        MainWindow.setWindowTitle(_translate("MainWindow", "Explorable SR"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.fileToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        # self.drawingToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        # self.fontToolbar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionClearImage.setText(_translate("MainWindow", "Clear Image"))
        self.actionOpenImage.setText(_translate("MainWindow", "Open Image..."))
        self.actionSaveImage.setText(_translate("MainWindow", "Save Image As..."))
        self.actionSaveImageAndData.setText(_translate("MainWindow", "Save Image & Z map"))
        self.actionInvertColors.setText(_translate("MainWindow", "Invert Colors"))
        self.actionFlipHorizontal.setText(_translate("MainWindow", "Flip Horizontal"))
        self.actionFlipVertical.setText(_translate("MainWindow", "Flip Vertical"))
        self.actionNewImage.setText(_translate("MainWindow", "New Image"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionItalic.setText(_translate("MainWindow", "Italic"))
        self.actionItalic.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionFillShapes.setText(_translate("MainWindow", "Fill Shapes?"))

